### ISSUE TITLE
iOS: keyboard is on top  of the TextInputs

### ISSUE THREAD

**Issue by aldo-rl** [aldo-rl/mora#1]
When the keyboard is open, it is on top of the TextInputs. This is a problem
because the users can't see what they is typing.

https://user-images.githubusercontent.com/68615596/193424367-3f58a2f4-04d5-4311-b15c-eed1e802cb61.mp4

Please, leave a comment if you want to work on this issue so I can assign it to you.

**Comment by SoldierCorp** [comment]
Hi @aldo-rl!

I would like to work on this issue, could you please assign it to me 🙂?

**Comment by aldo-rl** [comment]
@SoldierCorp Of course, I already assigned it to you.
